var searchData=
[
  ['naggymock_0',['NaggyMock',['../classtesting_1_1NaggyMock.html',1,'testing']]],
  ['name_1',['name',['../structdrm__version.html#a76bb6feb5b5b654b837f7dd2e8669b70',1,'drm_version::name()'],['../structdrm__gem__flink.html#ab980f86b119500b9c37fb2e26c3726a0',1,'drm_gem_flink::name()'],['../structdrm__gem__open.html#a346f1cd8f00cdf8ee5247364c870a259',1,'drm_gem_open::name()'],['../structdrm__version.html#afac6d5c52ee6060aa7eed5bf44172bf5',1,'drm_version::name()']]],
  ['name_5flen_2',['name_len',['../structdrm__version.html#a180ab1852b477291670bbc3ffc637c5d',1,'drm_version']]],
  ['namedvalidator_3',['NamedValidator',['../structNEO_1_1NamedValidator.html',1,'NEO']]],
  ['nativearray_4',['NativeArray',['../classtesting_1_1internal_1_1NativeArray.html',1,'testing::internal']]],
  ['negativefailallocationcommandenqueuebasefixture_5',['NegativeFailAllocationCommandEnqueueBaseFixture',['../structNEO_1_1NegativeFailAllocationCommandEnqueueBaseFixture.html',1,'NEO']]],
  ['next_5fextension_6',['next_extension',['../structi915__user__extension.html#a8ef82be9df0752e092c3a29eca734600',1,'i915_user_extension']]],
  ['nicemock_7',['NiceMock',['../classtesting_1_1NiceMock.html',1,'testing']]],
  ['nicemock_3c_20drmmockimpl_20_3e_8',['NiceMock&lt; DrmMockImpl &gt;',['../classtesting_1_1NiceMock.html',1,'testing']]],
  ['nl_5fmsg_9',['nl_msg',['../structnl__msg.html',1,'']]],
  ['nl_5fsock_10',['nl_sock',['../structnl__sock.html',1,'']]],
  ['nlapi_11',['NlApi',['../classL0_1_1NlApi.html',1,'L0']]],
  ['nocleanupwddmmock_12',['NoCleanupWddmMock',['../structNEO_1_1NoCleanupWddmMock.html',1,'NEO']]],
  ['nocompilerinterfacerootdeviceenvironment_13',['NoCompilerInterfaceRootDeviceEnvironment',['../classNoCompilerInterfaceRootDeviceEnvironment.html',1,'']]],
  ['node_14',['Node',['../structNEO_1_1Yaml_1_1Node.html',1,'NEO::Yaml']]],
  ['noncopyableclass_15',['NonCopyableClass',['../classNEO_1_1NonCopyableClass.html',1,'NEO']]],
  ['noncopyableormovableclass_16',['NonCopyableOrMovableClass',['../classNEO_1_1NonCopyableOrMovableClass.html',1,'NEO']]],
  ['nondefaultioctlssupported_17',['NonDefaultIoctlsSupported',['../structNonDefaultIoctlsSupported.html',1,'']]],
  ['noreadexpectvalues_18',['NoReadExpectValues',['../structCmdServicesMemTraceMemoryCompare_1_1NoReadExpectValues.html',1,'CmdServicesMemTraceMemoryCompare::NoReadExpectValues'],['../structCmdServicesMemTraceRegisterCompare_1_1NoReadExpectValues.html',1,'CmdServicesMemTraceRegisterCompare::NoReadExpectValues']]],
  ['normalizedtest_19',['NormalizedTest',['../structNormalizedTest.html',1,'']]],
  ['notifyevictparametrization_20',['NotifyEvictParametrization',['../structNEO_1_1KmDafListenerMock_1_1NotifyEvictParametrization.html',1,'NEO::KmDafListenerMock']]],
  ['notifylockparametrization_21',['NotifyLockParametrization',['../structNEO_1_1KmDafListenerMock_1_1NotifyLockParametrization.html',1,'NEO::KmDafListenerMock']]],
  ['notifymakeresidentparametrization_22',['NotifyMakeResidentParametrization',['../structNEO_1_1KmDafListenerMock_1_1NotifyMakeResidentParametrization.html',1,'NEO::KmDafListenerMock']]],
  ['notifymapgpuvaparametrization_23',['NotifyMapGpuVAParametrization',['../structNEO_1_1KmDafListenerMock_1_1NotifyMapGpuVAParametrization.html',1,'NEO::KmDafListenerMock']]],
  ['notifyunlockparametrization_24',['NotifyUnlockParametrization',['../structNEO_1_1KmDafListenerMock_1_1NotifyUnlockParametrization.html',1,'NEO::KmDafListenerMock']]],
  ['notifyunmapgpuvaparametrization_25',['NotifyUnmapGpuVAParametrization',['../structNEO_1_1KmDafListenerMock_1_1NotifyUnmapGpuVAParametrization.html',1,'NEO::KmDafListenerMock']]],
  ['notifywritetargetparametrization_26',['NotifyWriteTargetParametrization',['../structNEO_1_1KmDafListenerMock_1_1NotifyWriteTargetParametrization.html',1,'NEO::KmDafListenerMock']]],
  ['nullimage_27',['NullImage',['../structNullImage.html',1,'']]],
  ['nullobjecterrormapper_28',['NullObjectErrorMapper',['../structNullObjectErrorMapper.html',1,'']]],
  ['nullobjecterrormapper_3c_20cl_5fcommand_5fqueue_20_3e_29',['NullObjectErrorMapper&lt; cl_command_queue &gt;',['../structNullObjectErrorMapper_3_01cl__command__queue_01_4.html',1,'']]],
  ['nullobjecterrormapper_3c_20cl_5fcontext_20_3e_30',['NullObjectErrorMapper&lt; cl_context &gt;',['../structNullObjectErrorMapper_3_01cl__context_01_4.html',1,'']]],
  ['nullobjecterrormapper_3c_20cl_5fdevice_5fid_20_3e_31',['NullObjectErrorMapper&lt; cl_device_id &gt;',['../structNullObjectErrorMapper_3_01cl__device__id_01_4.html',1,'']]],
  ['nullobjecterrormapper_3c_20cl_5fevent_20_3e_32',['NullObjectErrorMapper&lt; cl_event &gt;',['../structNullObjectErrorMapper_3_01cl__event_01_4.html',1,'']]],
  ['nullobjecterrormapper_3c_20cl_5fkernel_20_3e_33',['NullObjectErrorMapper&lt; cl_kernel &gt;',['../structNullObjectErrorMapper_3_01cl__kernel_01_4.html',1,'']]],
  ['nullobjecterrormapper_3c_20cl_5fmem_20_3e_34',['NullObjectErrorMapper&lt; cl_mem &gt;',['../structNullObjectErrorMapper_3_01cl__mem_01_4.html',1,'']]],
  ['nullobjecterrormapper_3c_20cl_5fplatform_5fid_20_3e_35',['NullObjectErrorMapper&lt; cl_platform_id &gt;',['../structNullObjectErrorMapper_3_01cl__platform__id_01_4.html',1,'']]],
  ['nullobjecterrormapper_3c_20cl_5fprogram_20_3e_36',['NullObjectErrorMapper&lt; cl_program &gt;',['../structNullObjectErrorMapper_3_01cl__program_01_4.html',1,'']]],
  ['nullobjecterrormapper_3c_20cl_5fsampler_20_3e_37',['NullObjectErrorMapper&lt; cl_sampler &gt;',['../structNullObjectErrorMapper_3_01cl__sampler_01_4.html',1,'']]],
  ['nullobjecterrormapper_3c_20const_20void_20_2a_20_3e_38',['NullObjectErrorMapper&lt; const void * &gt;',['../structNullObjectErrorMapper_3_01const_01void_01_5_01_4.html',1,'']]],
  ['nullobjecterrormapper_3c_20void_20_2a_20_3e_39',['NullObjectErrorMapper&lt; void * &gt;',['../structNullObjectErrorMapper_3_01void_01_5_01_4.html',1,'']]],
  ['nullsurface_40',['NullSurface',['../classNEO_1_1NullSurface.html',1,'NEO']]],
  ['num_5fengines_41',['num_engines',['../structdrm__i915__query__engine__info.html#aed82aaae60877da1825ece6285b934df',1,'drm_i915_query_engine_info::num_engines()'],['../structprelim__drm__i915__query__engine__info.html#a08cddfb14a44d0fa07bf3ec8ee5a9f3c',1,'prelim_drm_i915_query_engine_info::num_engines()']]],
  ['num_5fitems_42',['num_items',['../structdrm__i915__query.html#a3fa5ae082ea50539893dbf859af75c29',1,'drm_i915_query']]],
  ['num_5fproperties_43',['num_properties',['../structdrm__i915__perf__open__param.html#a126cec5196effefb5d272c0a534d389b',1,'drm_i915_perf_open_param']]],
  ['num_5fregions_44',['num_regions',['../structdrm__i915__query__memory__regions.html#a2d2fce7446d823592d67a51ea745844f',1,'drm_i915_query_memory_regions::num_regions()'],['../structdrm__i915__gem__create__ext__memory__regions.html#a49f257bf91bb0a49cdefa19ea9d0c965',1,'drm_i915_gem_create_ext_memory_regions::num_regions()'],['../structprelim__drm__i915__query__memory__regions.html#a6be5846423e02468018505f0c1dc1cb2',1,'prelim_drm_i915_query_memory_regions::num_regions()']]],
  ['num_5fsiblings_45',['num_siblings',['../structi915__context__engines__parallel__submit.html#aa0549a7337dac60b7a904823affea0af',1,'i915_context_engines_parallel_submit']]],
  ['nv12extensionsupportedimageformatstest_46',['NV12ExtensionSupportedImageFormatsTest',['../structNV12ExtensionSupportedImageFormatsTest.html',1,'']]],
  ['nv12imagetest_47',['Nv12ImageTest',['../classNv12ImageTest.html',1,'']]]
];
